# Generated by Django 3.0.5 on 2020-04-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200415_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='todo_object',
        ),
    ]
